# Generated by Django 4.1 on 2022-08-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_rename_subscribers_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'MySubscriber', 'verbose_name_plural': 'A lot of Subscribers'},
        ),
    ]
